# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='microservice.proto',
  package='microservice',
  syntax='proto3',
  serialized_pb=_b('\n\x12microservice.proto\x12\x0cmicroservice\"\x18\n\x06Numero\x12\x0e\n\x06numero\x18\x01 \x01(\x05\"\xa1\x01\n\x04News\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x11\n\tpublisher\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\r\n\x05story\x18\x06 \x01(\t\x12\x10\n\x08hostname\x18\x07 \x01(\t\x12\x12\n\ntime_stamp\x18\x08 \x01(\t\x12\x17\n\x0fnumero_accessos\x18\t \x01(\x05\x32H\n\x0cMicroservice\x12\x38\n\x08ListNews\x12\x14.microservice.Numero\x1a\x12.microservice.News\"\x00\x30\x01\x62\x06proto3')
)




_NUMERO = _descriptor.Descriptor(
  name='Numero',
  full_name='microservice.Numero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numero', full_name='microservice.Numero.numero', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=60,
)


_NEWS = _descriptor.Descriptor(
  name='News',
  full_name='microservice.News',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='microservice.News.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='microservice.News.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='microservice.News.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher', full_name='microservice.News.publisher', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='microservice.News.category', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='story', full_name='microservice.News.story', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='microservice.News.hostname', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='microservice.News.time_stamp', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numero_accessos', full_name='microservice.News.numero_accessos', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=224,
)

DESCRIPTOR.message_types_by_name['Numero'] = _NUMERO
DESCRIPTOR.message_types_by_name['News'] = _NEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numero = _reflection.GeneratedProtocolMessageType('Numero', (_message.Message,), dict(
  DESCRIPTOR = _NUMERO,
  __module__ = 'microservice_pb2'
  # @@protoc_insertion_point(class_scope:microservice.Numero)
  ))
_sym_db.RegisterMessage(Numero)

News = _reflection.GeneratedProtocolMessageType('News', (_message.Message,), dict(
  DESCRIPTOR = _NEWS,
  __module__ = 'microservice_pb2'
  # @@protoc_insertion_point(class_scope:microservice.News)
  ))
_sym_db.RegisterMessage(News)



_MICROSERVICE = _descriptor.ServiceDescriptor(
  name='Microservice',
  full_name='microservice.Microservice',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=226,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListNews',
    full_name='microservice.Microservice.ListNews',
    index=0,
    containing_service=None,
    input_type=_NUMERO,
    output_type=_NEWS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MICROSERVICE)

DESCRIPTOR.services_by_name['Microservice'] = _MICROSERVICE

# @@protoc_insertion_point(module_scope)
