# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import microservice_pb2 as microservice__pb2


class MicroserviceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListNews = channel.unary_stream(
        '/microservice.Microservice/ListNews',
        request_serializer=microservice__pb2.Numero.SerializeToString,
        response_deserializer=microservice__pb2.News.FromString,
        )


class MicroserviceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListNews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MicroserviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListNews': grpc.unary_stream_rpc_method_handler(
          servicer.ListNews,
          request_deserializer=microservice__pb2.Numero.FromString,
          response_serializer=microservice__pb2.News.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'microservice.Microservice', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
